/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'timestamp' : bigint,
}
export interface Assessment {
  'id' : bigint,
  'title' : string,
  'subject' : string,
  'date' : bigint,
  'description' : string,
  'timestamp' : bigint,
  'classLevel' : string,
  'fileUrl' : [] | [string],
}
export interface Inquiry {
  'id' : bigint,
  'name' : string,
  'message' : string,
  'timestamp' : bigint,
  'classLevel' : string,
}
export interface _SERVICE {
  'addAnnouncement' : ActorMethod<[string, string], bigint>,
  'addAssessment' : ActorMethod<
    [string, string, string, bigint, string, [] | [string]],
    bigint
  >,
  'addInquiry' : ActorMethod<[string, string, string], bigint>,
  'getAnnouncement' : ActorMethod<[bigint], Announcement>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAssessment' : ActorMethod<[bigint], Assessment>,
  'getAssessments' : ActorMethod<[], Array<Assessment>>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getInquiriesOwner' : ActorMethod<[], Array<Inquiry>>,
  'getOwner' : ActorMethod<[], [] | [Principal]>,
  'setOwner' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];