/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Assessment = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'classLevel' : IDL.Text,
  'fileUrl' : IDL.Opt(IDL.Text),
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'classLevel' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addAssessment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAssessment' : IDL.Func([IDL.Nat], [Assessment], ['query']),
  'getAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getInquiriesOwner' : IDL.Func([], [IDL.Vec(Inquiry)], []),
  'getOwner' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'setOwner' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Assessment = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'classLevel' : IDL.Text,
    'fileUrl' : IDL.Opt(IDL.Text),
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'classLevel' : IDL.Text,
  });
  
  return IDL.Service({
    'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addAssessment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAssessment' : IDL.Func([IDL.Nat], [Assessment], ['query']),
    'getAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getInquiriesOwner' : IDL.Func([], [IDL.Vec(Inquiry)], []),
    'getOwner' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'setOwner' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };